spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kadimar_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: kadimar@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
          fetch_size: 25
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  security:
    basic:
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:your-secret-key-here-should-be-very-long-and-secure-in-production}
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    com.kadimar.management: DEBUG
    org.hibernate.SQL: DEBUG
